npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

packageExtensions:
  '@algolia/autocomplete-core@1.17.7':
    dependencies:
      '@algolia/client-search': latest
      algoliasearch: latest
      search-insights: latest
  '@algolia/autocomplete-plugin-algolia-insights@1.17.7':
    dependencies:
      '@algolia/client-search': latest
      algoliasearch: latest
  '@docsearch/react@3.8.2':
    dependencies:
      '@algolia/client-search': latest
  sandpack-vue3@3.1.11:
    dependencies:
      '@lezer/common': latest

yarnPath: .yarn/releases/yarn-4.12.0.cjs
