npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

packageExtensions:
  '@algolia/autocomplete-core@1.17.7':
    dependencies:
      '@algolia/client-search': 5.46.3
      algoliasearch: 5.46.3
      search-insights: 2.17.3
  '@algolia/autocomplete-plugin-algolia-insights@1.17.7':
    dependencies:
      '@algolia/client-search': 5.46.3
      algoliasearch: 5.46.3
  '@docsearch/react@3.8.2':
    dependencies:
      '@algolia/client-search': 5.46.3
  sandpack-vue3@3.1.11:
    dependencies:
      '@lezer/common': 1.2.3
  vitepress@*:
    dependencies:
      '@vue/server-renderer': 3.5.33

yarnPath: .yarn/releases/yarn-4.12.0.cjs
