npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

packageExtensions:
  '@algolia/autocomplete-core@1.9.3':
    dependencies:
      '@algolia/client-search': latest
      algoliasearch: latest
      search-insights: latest
  '@algolia/autocomplete-plugin-algolia-insights@1.9.3':
    dependencies:
      '@algolia/client-search': latest
      algoliasearch: latest
  '@docsearch/react@3.6.1':
    dependencies:
      '@algolia/client-search': latest
  '@vueuse/core@10.11.1':
    dependencies:
      vue: latest
  '@vueuse/integrations@10.11.1':
    dependencies:
      vue: latest
  '@vueuse/shared@10.11.1':
    dependencies:
      vue: latest
  sandpack-vue3@3.1.11:
    dependencies:
      '@lezer/common': latest

yarnPath: .yarn/releases/yarn-4.9.1.cjs
