export { clamp } from './clamp.ts';
export { inRange } from './inRange.ts';
export { mean } from './mean.ts';
export { meanBy } from './meanBy.ts';
export { random } from './random.ts';
export { randomInt } from './randomInt.ts';
export { round } from './round.ts';
export { sum } from './sum.ts';
export { range } from './range.ts';
