name: Broken link checker

on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:
    inputs: { url: { description: 'URL to check', required: false, default: 'https://es-toolkit.dev' } }

permissions: read-all

jobs:
  broken-link-checker:
    if: github.repository == 'toss/es-toolkit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: corepack enable
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install
      - name: Check broken link
        env:
          url: ${{ github.event.inputs.url || 'https://es-toolkit.dev' }}
        run: yarn blc $url --ro
