name: Broken link checker

on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:
    inputs: { url: { description: 'URL to check', required: false, default: 'https://es-toolkit.dev' } }

permissions: read-all

jobs:
  broken-link-checker:
    if: github.repository == 'toss/es-toolkit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check broken link
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --verbose --no-progress --exclude '^https://www\.npmjs\.com/package/es-toolkit$' ${{ github.event.inputs.url || 'https://es-toolkit.dev' }}
          fail: true
