name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

permissions: read-all

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: v2.x
      - run: deno publish --dry-run
