name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x
      - run: deno publish --dry-run
