name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

permissions: read-all

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x
      - run: deno publish --dry-run
