name: Test Compatibility Layer on Node 6

on:
  push:
    branches:
      - 'node-6'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '6'
      - name: Check node, npm version
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: npx jest
