name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions: read-all

jobs:
  release:
    if: github.repository == 'toss/es-toolkit'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: v1.x
      - name: Check environment
        run: |
          node -v
          npm -v
          yarn -v
      - if: github.ref_type == 'branch'
        run: |
          jq \
            --arg build "$GITHUB_RUN_NUMBER" \
            --arg commit "${GITHUB_SHA::8}" \
            '.version = .version + "-dev." + $build + "+" + $commit' \
            package.json > package.json.tmp
          mv package.json.tmp package.json
          jq \
            --arg build "$GITHUB_RUN_NUMBER" \
            --arg commit "${GITHUB_SHA::8}" \
            '.version = .version + "-dev." + $build + "+" + $commit' \
            jsr.json > jsr.json.tmp
          mv jsr.json.tmp jsr.json
      - run: yarn install
      - run: yarn test
      - run: 'mkdir -p out && yarn pack --out out/%s-%v.tgz'
      - name: Check Package Entrypoints
        run: 'yarn attw out/*.tgz'
      - id: extract-changelog
        uses: dahlia/submark@e3fa710655cb531b68fbfe912c9603aea136fff4
        with:
          input-file: CHANGELOG.md
          heading-level: 2
          heading-title-text: version ${{ github.ref_name }}
          ignore-case: true
          omit-heading: true
      - run: 'cat ${{ steps.extract-changelog.outputs.output-file }}'
      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ steps.extract-changelog.outputs.output-file }}
          repository: toss/es-toolkit
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: out/*.tgz
      - name: Publish to registry
        if: |
          github.event_name == 'push' &&
          (github.ref_type == 'tag' || github.ref == 'refs/heads/main')
        run: |
          set -ex
          if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
            npm publish --provenance --access public *.tgz
          else
            npm publish --provenance --access public --tag dev *.tgz
          fi
          deno publish --allow-dirty --unstable-sloppy-imports
        working-directory: ${{ github.workspace }}/out/

  deploy-docs:
    if: github.repository == 'toss/es-toolkit' && github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Deploy a docs site
        run: yarn vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
