name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 4 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    if: github.repository == 'toss/es-toolkit'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: results.sarif
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: scorecard-results
          path: results.sarif
          if-no-files-found: error
          retention-days: 5
